Dim rundll32command As String
Input rundll32command
If rundll32command = "advapi32.dll, ProcessIdleTasks" Then shell("rundll32.exe advapi32.dll, ProcessIdleTasks") end if
If rundll32command = "devmgr.dll, DeviceManager_Execute" Then shell("rundll32.exe devmgr.dll, DeviceManager_Execute") end if
If rundll32command = "inetcpl.cpl, ClearMyTracksByProcess 1" Then shell("rundll32.exe inetcpl.cpl, ClearMyTracksByProcess 1") end if
If rundll32command = "inetcpl.cpl, ClearMyTracksByProcess 16" Then shell("rundll32.exe inetcpl.cpl, ClearMyTracksByProcess 16") end if
If rundll32command = "inetCpl.cpl, ClearMyTracksByProcess 16384" Then shell("rundll32.exe inetCpl.cpl, ClearMyTracksByProcess 16384") end if
If rundll32command = "inetcpl.cpl, ClearMyTracksByProcess 2" Then shell("rundll32.exe inetcpl.cpl, ClearMyTracksByProcess 2") end if
If rundll32command = "inetcpl.cpl, ClearMyTracksByProcess 255" Then shell("rundll32.exe inetcpl.cpl, ClearMyTracksByProcess 32") end if
If rundll32command = "inetcpl.cpl, ClearMyTracksByProcess 32" Then shell("rundll32.exe inetcpl.cpl, ClearMyTracksByProcess 32") end if
If rundll32command = "inetcpl.cpl, ClearMyTracksByProcess 4351" Then shell("rundll32.exe inetcpl.cpl, ClearMyTracksByProcess 4351") end if
If rundll32command = "inetcpl.cpl, ClearMyTracksByProcess 8" Then shell("rundll32.exe inetcpl.cpl, ClearMyTracksByProcess 8") end if
If rundll32command = "keymgr.dll, KRShowKeyMgr" Then shell("rundll32.exe keymgr.dll, KRShowKeyMgr") end if
If rundll32command = "keymgr.dll, PRShowSaveWizardExW" Then shell("rundll32.exe keymgr.dll, PRShowSaveWizardExW") end if
If rundll32command = "msrating.dll, RatingSetupUI" Then shell("rundll32.exe msrating.dll, RatingSetupUI") end if
If rundll32command = "newdev.dll, DeviceInternetSettingUi" Then shell("rundll32.exe newdev.dll, DeviceInternetSettingUi") end if
If rundll32command = "powrprof.dll, SetSuspendState" Then shell("rundll32.exe powrprof.dll, SetSuspendState") end if
If rundll32command = "printui.dll, PrintUIEntry /?" Then shell("rundll32.exe printui.dll, PrintUIEntry /?") end if
If rundll32command = "pwlauncher.dll, ShowPortableWorkspaceLauncherConfigurationUX" Then shell("rundll32.exe pwlauncher.dll, ShowPortableWorkspaceLauncherConfigurationUX") end if
If rundll32command = "shdocvw.dll, DoOrganizeFavDlg" Then shell("rundll32.exe shdocvw.dll, DoOrganizeFavDlg") end if
If rundll32command = "shell32.dll, Control_Options 2" Then shell("rundll32.exe shell32.dll, Control_Options 2") end if
If rundll32command = "shell32.dll, Control_RunDLL" Then shell("rundll32.exe shell32.dll, Control_RunDLL") end if end if
If rundll32command = "shell32.dll, Control_RunDLL %SystemRoot%\System32\Speech\SpeechUX\sapi.cpl,,1" Then shell("rundll32.exe shell32.dll, Control_RunDLL %SystemRoot%\System32\Speech\SpeechUX\sapi.cpl,,1") end if
If rundll32command = "shell32.dll, Control_RunDLL access.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL access.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL access.cpl,,3" Then shell("rundll32.exe shell32.dll, Control_RunDLL access.cpl,,3") end if
If rundll32command = "shell32.dll, Control_RunDLL appwiz.cpl,,0" Then shell("rundll32.exe shell32.dll, Control_RunDLL appwiz.cpl,,0") end if
If rundll32command = "shell32.dll, Control_RunDLL appwiz.cpl,,2" Then shell("rundll32.exe shell32.dll, Control_RunDLL appwiz.cpl,,2") end if
If rundll32command = "shell32.dll, Control_RunDLL appwiz.cpl,,3" Then shell("rundll32.exe shell32.dll, Control_RunDLL appwiz.cpl,,3") end if
If rundll32command = "shell32.dll, Control_RunDLL cscui.dll,,0" Then shell("rundll32.exe shell32.dll, Control_RunDLL cscui.dll,,0") end if
If rundll32command = "shell32.dll, Control_RunDLL cscui.dll,,1" Then shell("rundll32.exe shell32.dll, Control_RunDLL cscui.dll,,1") end if
If rundll32command = "shell32.dll, Control_RunDLL cscui.dll,,2" Then shell("rundll32.exe shell32.dll, Control_RunDLL cscui.dll,,2") end if
If rundll32command = "shell32.dll, Control_RunDLL cscui.dll,,3" Then shell("rundll32.exe shell32.dll, Control_RunDLL cscui.dll,,3") end if
If rundll32command = "shell32.dll, Control_RunDLL desk.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL desk.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL desk.cpl,,0" Then shell("rundll32.exe shell32.dll, Control_RunDLL desk.cpl,,0") end if
If rundll32command = "shell32.dll, Control_RunDLL desk.cpl,,1" Then shell("rundll32.exe shell32.dll, Control_RunDLL desk.cpl,,1") end if
If rundll32command = "shell32.dll, Control_RunDLL desk.cpl,,2" Then shell("rundll32.exe shell32.dll, Control_RunDLL desk.cpl,,2") end if
If rundll32command = "shell32.dll, Control_RunDLL desk.cpl,Advanced,@Advanced" Then shell("rundll32.exe shell32.dll, Control_RunDLL desk.cpl,Advanced,@Advanced") end if
If rundll32command = "shell32.dll, Control_RunDLL firewall.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL firewall.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL hotPlug.dll" Then shell("rundll32.exe shell32.dll, Control_RunDLL hotPlug.dll") end if
If rundll32command = "shell32.dll, Control_RunDLL inetcpl.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL inetcpl.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL inetcpl.cpl,,1" Then shell("rundll32.exe shell32.dll, Control_RunDLL inetcpl.cpl,,1") end if
If rundll32command = "shell32.dll, Control_RunDLL inetcpl.cpl,,2" Then shell("rundll32.exe shell32.dll, Control_RunDLL inetcpl.cpl,,2") end if
If rundll32command = "shell32.dll, Control_RunDLL inetcpl.cpl,,3" Then shell("rundll32.exe shell32.dll, Control_RunDLL inetcpl.cpl,,3") end if
If rundll32command = "shell32.dll, Control_RunDLL inetcpl.cpl,,4" Then shell("rundll32.exe shell32.dll, Control_RunDLL inetcpl.cpl,,4") end if
If rundll32command = "shell32.dll, Control_RunDLL inetcpl.cpl,,5" Then shell("rundll32.exe shell32.dll, Control_RunDLL inetcpl.cpl,,5") end if
If rundll32command = "shell32.dll, Control_RunDLL inetcpl.cpl,,6" Then shell("rundll32.exe shell32.dll, Control_RunDLL inetcpl.cpl,,6") end if
If rundll32command = "shell32.dll, Control_RunDLL input.dll,,{C07337D3-DB2C-4D0B-9A93-B722A6C106E2}" Then shell("rundll32.exe shell32.dll, Control_RunDLL input.dll,,{C07337D3-DB2C-4D0B-9A93-B722A6C106E2}") end if
If rundll32command = "shell32.dll, Control_RunDLL intl.cpl,,0" Then shell("rundll32.exe shell32.dll, Control_RunDLL intl.cpl,,0") end if
If rundll32command = "shell32.dll, Control_RunDLL intl.cpl,,1" Then shell("rundll32.exe shell32.dll, Control_RunDLL intl.cpl,,1") end if
If rundll32command = "shell32.dll, Control_RunDLL intl.cpl,,2" Then shell("rundll32.exe shell32.dll, Control_RunDLL intl.cpl,,2") end if
If rundll32command = "shell32.dll, Control_RunDLL irprops.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL irprops.cpl") end if end if
If rundll32command = "shell32.dll, Control_RunDLL joy.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL joy.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL main.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL main.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL main.cpl @0,0" Then shell("rundll32.exe shell32.dll, Control_RunDLL main.cpl @0,0") end if
If rundll32command = "shell32.dll, Control_RunDLL main.cpl @1" Then shell("rundll32.exe shell32.dll, Control_RunDLL main.cpl @1") end if
If rundll32command = "shell32.dll, Control_RunDLL main.cpl,,1" Then shell("rundll32.exe shell32.dll, Control_RunDLL main.cpl,,1") end if
If rundll32command = "shell32.dll, Control_RunDLL main.cpl,,2" Then shell("rundll32.exe shell32.dll, Control_RunDLL main.cpl,,2") end if
If rundll32command = "shell32.dll, Control_RunDLL main.cpl,,3" Then shell("rundll32.exe shell32.dll, Control_RunDLL main.cpl,,3") end if
If rundll32command = "shell32.dll, Control_RunDLL main.cpl,,4" Then shell("rundll32.exe shell32.dll, Control_RunDLL main.cpl,,4") end if
If rundll32command = "shell32.dll, Control_RunDLL mmsys.cpl,,0" Then shell("rundll32.exe shell32.dll, Control_RunDLL mmsys.cpl,,0") end if
If rundll32command = "shell32.dll, Control_RunDLL mmsys.cpl,,1" Then shell("rundll32.exe shell32.dll, Control_RunDLL mmsys.cpl,,1") end if
If rundll32command = "shell32.dll, Control_RunDLL mmsys.cpl,,2" Then shell("rundll32.exe shell32.dll, Control_RunDLL mmsys.cpl,,2") end if
If rundll32command = "shell32.dll, Control_RunDLL mmsys.cpl,,3" Then shell("rundll32.exe shell32.dll, Control_RunDLL mmsys.cpl,,3") end if
If rundll32command = "shell32.dll, Control_RunDLL ncpa.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL ncpa.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL netSetup.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL netSetup.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL netSetup.cpl,@0,WNSW" Then shell("rundll32.exe shell32.dll, Control_RunDLL netSetup.cpl,@0,WNSW") end if
If rundll32command = "shell32.dll, Control_RunDLL nusrmgr.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL nusrmgr.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL odbccp32.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL odbccp32.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL powercfg.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL powercfg.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL srchadmin.dll" Then shell("rundll32.exe shell32.dll, Control_RunDLL srchadmin.dll") end if
If rundll32command = "shell32.dll, Control_RunDLL sysdm.cpl,,1" Then shell("rundll32.exe shell32.dll, Control_RunDLL sysdm.cpl,,1") end if
If rundll32command = "shell32.dll, Control_RunDLL sysdm.cpl,,2" Then shell("rundll32.exe shell32.dll, Control_RunDLL sysdm.cpl,,2") end if
If rundll32command = "shell32.dll, Control_RunDLL sysdm.cpl,,3" Then shell("rundll32.exe shell32.dll, Control_RunDLL sysdm.cpl,,3") end if
If rundll32command = "shell32.dll, Control_RunDLL sysdm.cpl,,4" Then shell("rundll32.exe shell32.dll, Control_RunDLL sysdm.cpl,,4") end if
If rundll32command = "shell32.dll, Control_RunDLL sysdm.cpl,,5" Then shell("rundll32.exe shell32.dll, Control_RunDLL sysdm.cpl,,5") end if
If rundll32command = "shell32.dll, Control_RunDLL tabletpc.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL tabletpc.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL timedate.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL timedate.cpl") end if
If rundll32command = "shell32.dll, Control_RunDLL timedate.cpl,,1" Then shell("rundll32.exe shell32.dll, Control_RunDLL timedate.cpl,,1") end if
If rundll32command = "shell32.dll, Control_RunDLL wscui.cpl" Then shell("rundll32.exe shell32.dll, Control_RunDLL wscui.cpl") end if
If rundll32command = "shell32.dll, OpenAs_RunDLL Any_File-name.ext" Then shell("rundll32.exe "shell32.dll, OpenAs_RunDLL Any_File-name.ext") end if
If rundll32command = "shell32.dll, Options_RunDLL 0" Then shell("rundll32.exe shell32.dll, Options_RunDLL 0") end if
If rundll32command = "shell32.dll, Options_RunDLL 1" Then shell("rundll32.exe shell32.dll, Options_RunDLL 1") end if
If rundll32command = "shell32.dll, Options_RunDLL 2" Then shell("rundll32.exe shell32.dll, Options_RunDLL 2") end if
If rundll32command = "shell32.dll, Options_RunDLL 3" Then shell("rundll32.exe shell32.dll, Options_RunDLL 3") end if
If rundll32command = "shell32.dll, Options_RunDLL 7" Then shell("rundll32.exe shell32.dll, Options_RunDLL 7") end if
If rundll32command = "shell32.dll, ShellAbout" Then shell("rundll32.exe shell32.dll, ShellAbout") end if
If rundll32command = "shell32.dll, ShellAboutW" Then shell("rundll32.exe shell32.dll, ShellAboutW") end if
If rundll32command = "shell32.dll, SHHelpShortcuts_RunDLL AddPrinter" Then shell("rundll32.exe shell32.dll, SHHelpShortcuts_RunDLL AddPrinter") end if
If rundll32command = "shell32.dll, SHHelpShortcuts_RunDLL Connect" Then shell("rundll32.exe shell32.dll, SHHelpShortcuts_RunDLL Connect") end if
If rundll32command = "shell32.dll, SHHelpShortcuts_RunDLL FontsFolder" Then shell("rundll32.exe shell32.dll, SHHelpShortcuts_RunDLL FontsFolder") end if
If rundll32command = "shell32.dll, SHHelpShortcuts_RunDLL PrintersFolder" Then shell("rundll32.exe shell32.dll, SHHelpShortcuts_RunDLL PrintersFolder") end if
If rundll32command = "shwebsvc.dll, AddNetPlaceRunDll" Then shell("rundll32.exe shwebsvc.dll, AddNetPlaceRunDll") end if
If rundll32command = "sysdm.cpl, EditEnvironmentVariables" Then shell("rundll32.exe sysdm.cpl, EditEnvironmentVariables") end if
If rundll32command = "tcpmonui.dll, LocalAddPortUI" Then shell("rundll32.exe tcpmonui.dll, LocalAddPortUI") end if
If rundll32command = "user32.dll, LockWorkStation" Then shell("rundll32.exe user32.dll, LockWorkStation") end if
If rundll32command = "user32.dll, SwapMouseButton" Then shell("rundll32.exe user32.dll, SwapMouseButton") end if
Sleep